UhaulEnabled: true
DriveMonitorEnabled: true
FarmMonitorEnabled: true
PlotterEnabled: true
ChiaPath: /media/ssd/chia/chia-blockchain

UHaul:
  StagingPaths:
    - /media/ext0/plot_staging 
    - /media/ext1/plot_staging 
    - /media/ext2/plot_staging 
    - /media/ssd/plot_staging
    - /media/ssd/plot_staging/madmax
  FinalPaths:
    - /media/farm/ext4/plots

DriveMonitor:
  TempPaths:
    - /media/ext0/plot_temp 
    - /media/ext1/plot_temp 
    - /media/ext2/plot_temp 
    - /media/ssd/plot_temp
    - /media/farm/ext3/plot_temp 
    - /media/farm/ext7/plot_temp 

  StagingPaths:
    - /media/ext0/plot_staging 
    - /media/ext1/plot_staging 
    - /media/ext2/plot_staging 
    - /media/ssd/plot_staging
    - /media/ssd/plot_staging/madmax

  FinalPaths:
    - /media/farm/ext0/plots
    - /media/farm/ext1/plots
    - /media/farm/ext2/plots
    - /media/farm/ext3/plots
    - /media/farm/ext4/plots
    - /media/farm/ext5/plots
    - /media/farm/ext6/plots
    - /media/farm/ext7/plots
    - /media/farm/ext8/plots
    - /media/farm/ext9/plots
    - /media/farm/ext10/plots
    - /media/farm/ext11/plots

Plotter:

  - tempPath: /media/ext0/plot_temp
    finalPath: /media/ext0/plot_staging
    startDelay: 0m
    maxActivePlotters: 3
    maxPhase1: 1
    minDelay: 6h
    ram: 16000
    cores: 4
    buckets: 32
    poolKey: xch1lkgyhem2zqhyyxzpdkqdp2r7dyuzst5ydm7sw0rerkepvtk2teesu9m2lp
    tag: ext0

  - tempPath: /media/ext1/plot_temp
    finalPath: /media/ext1/plot_staging
    startDelay: 90m
    maxActivePlotters: 3
    maxPhase1: 1
    minDelay: 6h
    ram: 16000
    cores: 4
    buckets: 32
    poolKey: xch1lkgyhem2zqhyyxzpdkqdp2r7dyuzst5ydm7sw0rerkepvtk2teesu9m2lp
    tag: ext1

  - tempPath: /media/ext2/plot_temp
    finalPath: /media/ext2/plot_staging
    startDelay: 1h
    maxActivePlotters: 3
    maxPhase1: 1
    minDelay: 3h
    ram: 16000
    cores: 4
    buckets: 32
    poolKey: xch1lkgyhem2zqhyyxzpdkqdp2r7dyuzst5ydm7sw0rerkepvtk2teesu9m2lp
    tag: ext2

