TempPaths:
  - /media/ext/plot_temp
  - /media/ssd/plot_temp

StagingPaths:
  - /media/ext/plot_staging
  - /media/ssd/plot_staging

UHaul:
  StagingPaths:
    - /media/ext/plot_staging 
    - /media/ssd/plot_staging
  FinalPaths:
    - /media/remote/ext2/plots
