TempPaths:
  - /media/ext/plot_temp
  - /media/ssd/plot_temp

StagingPaths:
  - /media/ext/plot_staging
  - /media/ssd/plot_staging

UHaul:
  StagingPaths:
    - /media/ext/plot_staging 
    - /media/ssd/plot_staging
  FinalPaths:
    - /media/remote/ext2/plots

Manager:
  - path: /media/ext/plot_staging
    maxPerPhase: 1
  - path: /media/ssd/plot_staging
    maxPerPhase: 2

